### ISSUE TITLE
iOS 16.4 iPadOS 16.4 版本下，apple tv+ 在启用字幕插件时无法打开视频

### ISSUE THREAD

**Issue by shenxianghong** [DualSubs/Universal#33]
没有使用 boxjs，直接用的插件

猜测应该和16.4版本有关系（更新之前是好的）

现在打开视频会提示“载入此内容时出现问题”，loon 中禁用 dualsubs 恢复正常。

此外，disney+ 正常使用。

![image](https://user-images.githubusercontent.com/35031258/229325968-093409c2-38b7-4d99-bbad-f080e74d9ee5.png)

**Comment by linpend** [comment]
同样问题

**Comment by VirgilClyne** [comment]
因iOS16.4起MitM政策变更，TV及Fitness平台，需要配合[ iRingo: 📺 TV app](https://github.com/VirgilClyne/iRingo/wiki/%F0%9F%93%BA-%EF%A3%BFTV)恢复支持

**Comment by jjaychen1e** [comment]
@VirgilClyne iOS 18.0 的设备也有这个问题，Apple TV 模块也开启了
